server:
  port: 8001
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
       
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /olx-masterdata
     
spring:
  application:
      name: masterdata-service
  zipkin:
    base-url: http://localhost:9411    
      
  config:
     import: configserver:http://localhost:7777